version: 0.1
Resources:
 - TargetService:
     Type: AWS::ECS::Service
     Properties:
       TaskDefinition: "arn:aws:ecs:us-west-2:074356481843:task-definition/devops:2"
       LoadBalancerInfo:
         ContainerName: "devops"
         ContainerPort: 80